# Generated by Django 4.2.3 on 2023-07-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
