# Generated by Django 4.2.3 on 2023-07-27 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_cart_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_otp",
        ),
    ]
