# Generated by Django 4.2.3 on 2023-08-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_cart_session_id_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="offer",
            field=models.IntegerField(default=0),
        ),
    ]
