# Generated by Django 4.2.3 on 2023-07-24 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_category_options_remove_product_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["image"]},
        ),
    ]
