# Generated by Django 4.2.3 on 2023-08-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
