# Generated by Django 4.2.3 on 2023-08-13 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_offer_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="product",
        ),
        migrations.AddField(
            model_name="category",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.offer",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.offer",
            ),
        ),
    ]
