# Generated by Django 4.2.3 on 2023-08-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_remove_offer_category_remove_offer_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="end_date",
        ),
    ]
