# Generated by Django 4.2.3 on 2023-08-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_home_address_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(default="ck", max_length=50),
            preserve_default=False,
        ),
    ]
