# Generated by Django 4.2.3 on 2023-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_wishlist_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="session_id",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
