# Generated by Django 4.2.3 on 2023-08-04 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="variation",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderProduct",
        ),
    ]
