# Generated by Django 4.2.3 on 2023-08-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_rename_ammount_paind_payment_amount_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="user",
        ),
    ]
