# Generated by Django 4.2.3 on 2023-08-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order placed", "Order placed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Order Pending",
                max_length=15,
            ),
        ),
    ]
