# Generated by Django 4.2.3 on 2023-08-09 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_alter_order_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
    ]
