# Generated by Django 4.2.3 on 2023-08-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_wishlist_wishlistitem"),
        ("order", "0010_order_coupon_price_order_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.address"
            ),
        ),
    ]
