# Generated by Django 4.2.3 on 2023-08-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_alter_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.IntegerField(default=0),
        ),
    ]
