# Generated by Django 4.2.3 on 2023-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_order_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session_id",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
